import React from 'react';
import { BarChart3, BookOpen, Box, ChevronDown, CircleDollarSign, FileSpreadsheet, PackagePlus, Settings, ShoppingCart, Sparkles, Smartphone, Undo2, UserRound, X } from 'lucide-react';
import type { StoreSettings } from '../types';
import type { AccountingTab } from './Header';
import type { PdfReportType } from './PdfReportModal';

interface Props { activeTab:AccountingTab; setActiveTab:(tab:AccountingTab)=>void; storeInfo:StoreSettings; isAdminUnlocked:boolean; onLockAdmin:()=>void; onOpenVazvrat:()=>void; onOpenExcelImport:()=>void; onOpenPdfReports:(type?:PdfReportType)=>void; onOpenInstallModal:()=>void; onOpenPhotoKirim?:()=>void; onOpenApiModal?:()=>void; isMobileOpen:boolean; onCloseMobile:()=>void; [key:string]:unknown; }

export const CompactSidebar:React.FC<Props>=({activeTab,setActiveTab,storeInfo,isAdminUnlocked,onLockAdmin,onOpenVazvrat,onOpenExcelImport,onOpenPdfReports,onOpenInstallModal,onOpenPhotoKirim,onOpenApiModal,isMobileOpen,onCloseMobile})=>{
 const go=(tab:AccountingTab)=>{setActiveTab(tab);onCloseMobile();};
 const item=(tab:AccountingTab,label:string,Icon:any)=><button type="button" onClick={()=>go(tab)} className={`w-full rounded-xl px-3 py-2.5 flex items-center gap-2.5 text-sm font-bold ${activeTab===tab?'bg-amber-400 text-stone-950':'text-stone-300 hover:bg-stone-900'}`}><Icon className="w-4 h-4"/>{label}</button>;
 if(!isAdminUnlocked)return <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-stone-950 p-3 text-white transition-transform lg:translate-x-0 ${isMobileOpen?'translate-x-0':'-translate-x-full'}`}><div className="flex items-center justify-between p-2"><strong>{storeInfo.name}</strong><button onClick={onCloseMobile}><X className="w-4 h-4"/></button></div>{item('chiqim','Sotuv va qidiruv',ShoppingCart)}{item('debts','Nasiya',BookOpen)}<button type="button" onClick={()=>{onOpenVazvrat();onCloseMobile();}} className="w-full rounded-xl px-3 py-2.5 flex items-center gap-2.5 text-sm font-bold text-stone-300 hover:bg-stone-900"><Undo2 className="w-4 h-4"/>Tovar qaytarish</button><button onClick={onLockAdmin} className="absolute bottom-4 left-3 right-3 rounded-xl border border-stone-700 py-2 text-xs">Hisobdan chiqish</button></aside>;
 return <><aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-stone-950 text-white border-r border-stone-800 flex flex-col transition-transform lg:translate-x-0 ${isMobileOpen?'translate-x-0':'-translate-x-full'}`}><div className="h-16 px-4 flex items-center gap-3 border-b border-stone-800"><div className="w-9 h-9 rounded-xl bg-amber-400 text-stone-950 flex items-center justify-center"><Smartphone className="w-5 h-5"/></div><div className="min-w-0 flex-1"><strong className="block text-sm truncate">{storeInfo.name}</strong><span className="text-[10px] text-emerald-400">● VPS ONLAYN</span></div><button onClick={onCloseMobile} className="lg:hidden"><X className="w-4 h-4"/></button></div>
 <nav className="flex-1 overflow-y-auto p-3 space-y-1">{item('chiqim','Sotuv kassasi',ShoppingCart)}{item('kirim','Tovar kirimi',PackagePlus)}{item('stock','Ombor',Box)}{item('report','Hisobotlar',BarChart3)}{item('debts','Mijoz nasiyalari',BookOpen)}{item('hisobchi','Sozlamalar',Settings)}
 <details className="pt-2 group"><summary className="list-none cursor-pointer rounded-xl px-3 py-2.5 flex items-center gap-2 text-sm font-bold text-stone-400 hover:bg-stone-900"><ChevronDown className="w-4 h-4 group-open:rotate-180"/>Qo‘shimcha</summary><div className="mt-1 pl-2 space-y-1 border-l border-stone-800">{item('journal','Harakatlar jurnali',BookOpen)}{item('supplier-debts','Ta’minotchi qarzi',CircleDollarSign)}{item('telegram-orders','Telegram zakazlar',Smartphone)}{item('ai-analyst','AI tahlilchi',Sparkles)}<button onClick={onOpenVazvrat} className="w-full px-3 py-2 text-left text-xs text-stone-400 flex gap-2"><Undo2 className="w-4 h-4"/>Tovar qaytarish</button><button onClick={onOpenExcelImport} className="w-full px-3 py-2 text-left text-xs text-stone-400 flex gap-2"><FileSpreadsheet className="w-4 h-4"/>Excel import</button>{onOpenPhotoKirim&&<button onClick={onOpenPhotoKirim} className="w-full px-3 py-2 text-left text-xs text-stone-400">📸 Foto kirim</button>}<button onClick={()=>onOpenPdfReports()} className="w-full px-3 py-2 text-left text-xs text-stone-400">📄 PDF hisobotlar</button><button onClick={onOpenInstallModal} className="w-full px-3 py-2 text-left text-xs text-stone-400">💻 Ilovani o‘rnatish</button>{onOpenApiModal&&<button onClick={onOpenApiModal} className="w-full px-3 py-2 text-left text-xs text-stone-400">API integratsiya</button>}</div></details></nav>
 <div className="p-3 border-t border-stone-800"><div className="rounded-xl bg-stone-900 px-3 py-2 flex items-center gap-2 text-xs"><UserRound className="w-4 h-4 text-amber-400"/><span className="flex-1">Rahbar</span><button onClick={onLockAdmin} className="text-stone-400">Chiqish</button></div></div></aside></>;
};
