import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Download, RefreshCw } from 'lucide-react';
import { downloadCSV, formatMoney } from '../utils/formatters';

type Report = any;
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tashkent', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date());
const moveDay = (date: string, days: number) => new Date(Date.parse(`${date}T12:00:00Z`) + days * 86400000).toISOString().slice(0,10);
const monthStart = (date: string) => `${date.slice(0,7)}-01`;
const yearStart = (date: string) => `${date.slice(0,4)}-01-01`;

export const ReportsDashboard: React.FC<{ onOpenPdfReports?: (type?: 'daily_sales') => void }> = ({ onOpenPdfReports }) => {
  const now = today(); const [from, setFrom] = useState(monthStart(now)); const [to, setTo] = useState(now);
  const [report, setReport] = useState<Report>(null); const [previous, setPrevious] = useState<Report>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const load = async () => { setLoading(true); setError(''); try { const response=await fetch(`/api/v1/reports/summary?from=${from}&to=${to}`,{cache:'no-store'}); const body=await response.json(); if(!response.ok) throw new Error(body.error); setReport(body.data); setPrevious(body.previous); } catch(e){setError(e instanceof Error?e.message:'Hisobot yuklanmadi.');} finally{setLoading(false);} };
  useEffect(()=>{load().catch(()=>undefined);},[]);
  const quick=(kind:string)=>{ const t=today(); let a=t,b=t; if(kind==='yesterday')a=b=moveDay(t,-1); if(kind==='3')a=moveDay(t,-2); if(kind==='7')a=moveDay(t,-6); if(kind==='month')a=monthStart(t); if(kind==='lastMonth'){b=moveDay(monthStart(t),-1);a=monthStart(b);} if(kind==='year')a=yearStart(t); if(kind==='lastYear'){const y=String(Number(t.slice(0,4))-1);a=`${y}-01-01`;b=`${y}-12-31`;} setFrom(a);setTo(b);setTimeout(()=>{},0);};
  const pct = (current:number, old:number) => old ? `${current>=old?'+':''}${(((current-old)/Math.abs(old))*100).toFixed(1)}%` : current ? '+100%' : '0%';
  const maxBar=useMemo(()=>Math.max(1,...(report?.timeline||[]).map((r:any)=>r.revenue)),[report]);
  const exportCsv=()=>{ if(!report)return; downloadCSV(`hisobot-${from}-${to}.csv`,[['MOBILEPARTS CRM HISOBOTI'],['Davr',from,to],['Tushum',String(report.sales.revenue)],['Yalpi foyda',String(report.sales.grossProfit)],['Chiqimlar',String(report.sales.expenses)],['Sof natija',String(report.sales.netProfit)],['Savdolar soni',String(report.sales.count)],[],['Xodim','Savdo soni','Tushum'],...report.employees.map((r:any)=>[r.name,String(r.sales),String(r.revenue)]),[],['Tovar','Soni','Tushum','Foyda'],...report.inventory.top.map((r:any)=>[r.name,String(r.quantity),String(r.revenue),String(r.profit)])]); };
  return <div className="space-y-4">
    <section className="rounded-2xl bg-stone-950 text-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black flex items-center gap-2"><BarChart3 className="text-amber-400"/>Mukammal hisobotlar</h2><p className="text-xs text-stone-400">Barcha hisob-kitob VPS serverida bajariladi</p></div><div className="flex gap-2"><button onClick={exportCsv} className="rounded-xl bg-stone-800 px-3 py-2 text-xs font-bold flex gap-1"><Download className="w-4 h-4"/>CSV</button>{onOpenPdfReports&&<button onClick={()=>onOpenPdfReports('daily_sales')} className="rounded-xl bg-amber-400 text-stone-950 px-3 py-2 text-xs font-black">PDF</button>}</div></div>
      <div className="mt-4 flex flex-wrap gap-1.5">{[['today','Bugun'],['yesterday','Kecha'],['3','3 kun'],['7','7 kun'],['month','Shu oy'],['lastMonth',"O‘tgan oy"],['year','Shu yil'],['lastYear',"O‘tgan yil"]].map(([k,l])=><button key={k} onClick={()=>quick(k)} className="rounded-lg bg-stone-800 px-2.5 py-1.5 text-[11px] hover:bg-stone-700">{l}</button>)}</div>
      <div className="mt-3 grid sm:grid-cols-[1fr_1fr_auto] gap-2"><label className="text-[10px] text-stone-400">Dan<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 w-full rounded-xl bg-stone-900 border border-stone-700 px-3 py-2 text-sm text-white"/></label><label className="text-[10px] text-stone-400">Gacha<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 w-full rounded-xl bg-stone-900 border border-stone-700 px-3 py-2 text-sm text-white"/></label><button onClick={load} disabled={loading} className="self-end rounded-xl bg-amber-400 text-stone-950 px-5 py-2.5 font-black text-sm flex justify-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Ko‘rsatish</button></div>
    </section>
    {error&&<div className="rounded-xl bg-rose-50 p-3 text-rose-700 text-sm font-bold">{error}</div>}
    {report&&<>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Tushum',report.sales.revenue,previous?.sales.revenue],['Yalpi foyda',report.sales.grossProfit,previous?.sales.grossProfit],['Chiqimlar',report.sales.expenses,previous?.sales.expenses],['Sof natija',report.sales.netProfit,previous?.sales.netProfit]].map(([label,value,old]:any)=><div key={label} className="rounded-2xl bg-white border p-4"><div className="text-xs text-stone-500">{label}</div><div className={`text-lg font-black ${label==='Sof natija'&&value<0?'text-rose-600':''}`}>{formatMoney(value)}</div><div className="text-[10px] text-stone-400">Oldingi davrga: {pct(value,old||0)}</div></div>)}</div>
      <div className="grid lg:grid-cols-3 gap-3"><section className="lg:col-span-2 rounded-2xl bg-white border p-4"><h3 className="font-black text-sm">Tushum dinamikasi • {report.range.grouping==='month'?'oylar':'kunlar'}</h3><div className="mt-4 h-44 flex items-end gap-1 overflow-x-auto">{report.timeline.length?report.timeline.map((r:any)=><div key={r.label} className="min-w-8 flex-1 h-full flex flex-col justify-end items-center" title={`${r.label}: ${formatMoney(r.revenue)}`}><div className="w-full max-w-12 bg-amber-400 rounded-t" style={{height:`${Math.max(4,r.revenue/maxBar*130)}px`}}/><span className="text-[8px] mt-1 text-stone-500 rotate-[-35deg] origin-top-left">{r.label.slice(5)}</span></div>):<div className="m-auto text-xs text-stone-400">Ma’lumot yo‘q</div>}</div></section>
      <section className="rounded-2xl bg-white border p-4"><h3 className="font-black text-sm">Savdo</h3><div className="mt-3 space-y-2 text-xs">{[['Savdolar',report.sales.count],['Sotilgan dona',report.sales.items],['O‘rtacha chek',formatMoney(report.sales.averageCheck)],['Naqd',formatMoney(report.sales.payments.cash)],['Click',formatMoney(report.sales.payments.click)],['Uzum',formatMoney(report.sales.payments.uzum)],['Nasiya',formatMoney(report.sales.payments.debt)]].map(([l,v]:any)=><div key={l} className="flex justify-between border-b pb-1"><span>{l}</span><strong>{v}</strong></div>)}</div></section></div>
      <div className="grid lg:grid-cols-3 gap-3"><section className="rounded-2xl bg-white border p-4"><h3 className="font-black text-sm">Ko‘p sotilgan tovarlar</h3>{report.inventory.top.slice(0,7).map((r:any)=><div key={r.id} className="flex justify-between text-xs py-1.5 border-b"><span className="truncate pr-2">{r.name}</span><strong>{r.quantity} ta</strong></div>)}{!report.inventory.top.length&&<p className="text-xs text-stone-400 mt-3">Ma’lumot yo‘q</p>}</section>
      <section className="rounded-2xl bg-white border p-4"><h3 className="font-black text-sm">Xodimlar savdosi</h3>{report.employees.map((r:any)=><div key={r.name} className="py-1.5 border-b text-xs"><div className="flex justify-between"><strong>{r.name}</strong><span>{formatMoney(r.revenue)}</span></div><div className="text-stone-400">{r.sales} ta savdo</div></div>)}{!report.employees.length&&<p className="text-xs text-stone-400 mt-3">Ma’lumot yo‘q</p>}</section>
      <section className="rounded-2xl bg-white border p-4"><h3 className="font-black text-sm">Nazorat</h3><div className="mt-3 space-y-2 text-xs">{[['Kirim qiymati',formatMoney(report.inventory.kirimCost)],['Sotilmagan tovar',`${report.inventory.unsoldCount} ta`],['Nasiya berilgan',formatMoney(report.debts.issued)],['Nasiya qaytarilgan',formatMoney(report.debts.paid)],['Jami qolgan qarz',formatMoney(report.debts.remaining)],['Smena kamomati',formatMoney(report.shifts.shortage)],['Smena ortiqchasi',formatMoney(report.shifts.surplus)]].map(([l,v]:any)=><div key={l} className="flex justify-between border-b pb-1"><span>{l}</span><strong>{v}</strong></div>)}</div></section></div>
    </>}
  </div>;
};
